agr/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import routers
#from attestation import views as attestation_views
from frontend import views as front_views
#from protheses import views as protheses_views
from django.conf import settings

admin.site.enable_nav_sidebar = False
#router = routers.DefaultRouter()
#router.register(r'attestations', attestation_views.AttestationView, 'attestation')
if not settings.DEBUG :
    handler404 = 'frontend.views.not_found_view'
    handler500 = 'frontend.views.not_found_view'
else:
    pass

urlpatterns = [
    #path('xadmin/', include(xadmin.site.urls)),
    #path('admin/', include('djadmin.urls')),
    path('', front_views.index, name="front"),
    #path('api/', include(router.urls)),
    path('espace/', front_views.espace, name="f-espace"),
    #path('coaph/', front_views.centres, name="f-centres-tout"),
    path('coaph/', front_views.centres, name="f-centres"),
    #path('coaph/<pk>/', front_views.centre, name="f-centre-sanspr"),
    path('coaph/<pk>/', front_views.centre, name="f-centre"),
    #path('attestation/', front_views.attestation, name="f-attestation"),
    #path('attestation/suivi/', front_views.suivi_attestation, name="f-suivi-attestation"),
    #path('attestation/suivi/<demande>/', front_views.suivi_attestation),
    #path('pdf/<int:attestation_pk>/', attestation_views.GeneratePdf.as_view()),
    path('agr/', front_views.agr, name="f-agr"),
    path('agr/suivi/', front_views.suivi_agr, name="f-suivi-agr"),
    path('backend/login/', front_views.backlogin, name="b-login"),
    path('backend/logout/', front_views.backlogout, name="b-logout"),
    path('backend/projets/', front_views.list_projets, name="f-projets"),
    path('backend/projets/<num_demande>/', front_views.details_agr, name="f-details-agr"),
    path('backend/projet/add/', front_views.add_projet, name="b-projet-add"),
    path('backend/dashboard/', front_views.dashboard, name="b-dashboard"),
    path('backend/psh/', front_views.list_psh, name="b-psh"),
    path('grappelli/', include('grappelli.urls')), # grappelli URL
    #path('admin/attestation/html/', attestation_views.ModelPdf.as_view()),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

grappelli/urls.py
# coding: utf-8

from django.urls import re_path

from .views.related import AutocompleteLookup, M2MLookup, RelatedLookup
from .views.switch import switch_user

urlpatterns = [

    # FOREIGNKEY & GENERIC LOOKUP
    re_path(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    re_path(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    re_path(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    re_path(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

]

centres/models.py
from django.db import models
from django.utils.translation import gettext as _
from agr.CHOICES_LISTS import *
from django.contrib.auth.models import Group, User
from django.conf import settings

MILIEU_CHOIX=(
    (1, _('Urbain')),
    (2, _('Rural')),
)

class Region(models.Model):
    nom = models.CharField(_('Nom'), max_length=300)
    nom_fr = models.CharField(_('Nom (fr)'), max_length=300, blank=True, null=True)

    def __str__(self):
        return self.nom

    @staticmethod
    def autocomplete_search_fields():
        return ("nom__icontains", "nom_fr__icontains",)

    class Meta:
        verbose_name = _('Région')
        verbose_name_plural = _('Régions')


class Province(models.Model):
    nom = models.CharField(_('Nom'), max_length=300)
    nom_fr = models.CharField(_('Nom (fr)'), max_length=300, blank=True, null=True)
    region = models.ForeignKey(
        Region,
        on_delete = models.CASCADE,
        related_name = "provinces",
        verbose_name = _("Région")
    )

    def __str__(self):
        return self.nom

    @staticmethod
    def autocomplete_search_fields():
        return ("nom__icontains", "nom_fr__icontains",)

    class Meta:
        verbose_name = _('Province')
        verbose_name_plural = _('Provinces')


class Commune(models.Model):
    nom = models.CharField(_('Nom'), max_length=300)
    nom_fr = models.CharField(_('Nom (fr)'), max_length=300, blank=True, null=True)
    region = models.ForeignKey(
        Region,
        on_delete = models.CASCADE,
        related_name = "communes",
        verbose_name = _("Région")
    )
    province = models.ForeignKey(
        Province,
        on_delete = models.CASCADE,
        related_name = "communes",
        verbose_name = _("Province")
    )
    milieu = models.PositiveSmallIntegerField(_('Milieu'), blank=True, null=True, choices=MILIEU_CHOIX, default=2)

    def __str__(self):
        return self.nom

    @staticmethod
    def autocomplete_search_fields():
        return ("nom__icontains", "nom_fr__icontains",)

    class Meta:
        verbose_name = _('Commune')
        verbose_name_plural = _('Communes')


class Centre(models.Model):
    nom = models.CharField(_('Nom'), max_length=200)
    region = models.ForeignKey(
        Region,
        verbose_name = _('Région'),
        related_name = "centres",
        on_delete = models.SET_NULL,
        null = True
    )
    province = models.ForeignKey(
        Province,
        verbose_name = _('Province'),
        related_name = "centres",
        on_delete = models.SET_NULL,
        null = True
    )
    commune = models.ForeignKey(
        Commune,
        verbose_name = _('Commune'),
        related_name = "centres",
        on_delete = models.SET_NULL,
        null = True
    )
    telephone = models.CharField(_('Téléphone'), max_length=10, blank=True)
    fax = models.CharField(_('Fax'), max_length=10, blank=True)
    email = models.EmailField(_('E-mail'), blank=True, null=True)
    adresse = models.CharField(_('Adresse'), max_length=300, blank=True)
    gerant = models.OneToOneField(
        Group,
        verbose_name = _('Gérant'),
        related_name = "centres",
        on_delete = models.SET_NULL,
        null = True
    )
    latitude = models.FloatField(_("latitude"), blank=True, null=True)
    longitude = models.FloatField(_("longitude"), blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.nom)

    class Meta:
        verbose_name = _('Centre')
        verbose_name_plural = _('Centres')

ORGANISMES=(
    ('EN REG', 'Entraide Nationale Regionale'),
    ('EN PROV', 'Entraide Nationale Provinciale'),
    ('ANAPEC REG', 'ANAPEC Regionale'),
    ('ANAPEC PROV', 'ANAPEC Provinciale'),
    ('ADS', 'ADS'),
    ('INDH', 'INDH'),
)

from django.db.models.signals import post_save
from django.dispatch import receiver

class Membre(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, related_name="membres", null=True)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, related_name="membres", null=True, blank=True)
    organisme = models.CharField(_('Organisme'), max_length=300, blank=True, choices=ORGANISMES)

    def __str__(self):
        return self.user.username

frontend/models.py
from django.db import models

# Create your models here.

projets/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from beneficiaires.models import Beneficiaire
from centres.models import Centre, Region, Province, Commune, Membre

NATURE_INDIV = 1
NATURE_COLLECT = 2
NATURE_PROJET=(
    (NATURE_INDIV, _('Individuel')),
    (NATURE_COLLECT, _('Collectif')),
)

FORME_AE = 1
FORME_PH = 2
FORME_SOC = 3
FORME_COOP = 4
FORME_AUTRE = 5
FORME_JURIDIQUE_CHOIX=(
    (FORME_AE, _('Auto-Entrepreneur')),
    (FORME_PH, _('RC/Personne Physique')),
    (FORME_SOC, _('Société')),
    (FORME_COOP, _('Coopérative')),
    (FORME_AUTRE, _('Autre')),
)

SECT_SERVICES = 1
SECT_COMMERCE = 2
SECT_INDUSTRIE = 3
SECT_AGRICULTURE = 4
SECT_ARTISANAT = 5
SECT_AUTRE = 6
SECTEUR_CHOIX=(
    (SECT_SERVICES, _('Services')),
    (SECT_COMMERCE, _('Commerce')),
    (SECT_INDUSTRIE, _('Industrie')),
    (SECT_AGRICULTURE, _('Agriculture')),
    (SECT_ARTISANAT, _('Artisanat')),
    (SECT_AUTRE, _('Autre')),
)

TYPES_PIECE_LOCAL=(
    (1, _('Propriété')),
    (2, _('Promesse de location')),
    (3, _('Contrat de location')),
    (4, _('Mise à disposition')),
    (5, _('Engagement')),
)

PIECE_CHOIX=(
    (True, _('Oui')),
    (False, _('Non')),
)

NATURE_TUTEUR=(
    (1, _('Bénéficiaire')),
    (2, _('Tuteur (Père)')),
    (3, _('Tuteur (Mère)')),
    (4, _('Autre')),
)
'''
class Structure(object):
    nom = models.CharField(_('Nom Structure'), max_length=500)


class Note(object):
    projet = models.ForeignKey()
'''

class Session(models.Model):
    titre = models.CharField(_('Titre'), max_length=500)
    date_ouverture = models.DateTimeField(_('Date Ouverture Session'))
    date_fermeture = models.DateTimeField(_('Date Fermeture Session'))
    ouverte = models.BooleanField(_('Session Ouverte'))

    def __str__(self):
        return self.titre

    def nb_projets(self):
        pass

    class Meta:
        verbose_name=_('Session')
        verbose_name_plural = _('Les Sessions')


class EtapeProjet(models.Model):
    nom = models.CharField(_('Etape'), max_length=50)
    ordre = models.PositiveSmallIntegerField(verbose_name=_('Ordre'), null=True)

    def __str__(self):
        return self.nom

    class Meta:
        verbose_name = _('Etape Demande')
        verbose_name_plural = _('Etapes Demande')


class Projet(models.Model):
    centre = models.ForeignKey(
        Centre,
        verbose_name = _('Centre'),
        related_name = 'projets',
        on_delete = models.SET_NULL,
        null = True
    )
    #beneficiaires = models.ManyToManyField(
    #    Beneficiaire,
    #    verbose_name = _("Bénéficiaire"),
    #)
    beneficiaire = models.ManyToManyField(
        Beneficiaire,
        verbose_name = _("Bénéficiaire"),
        through = 'ExecuteurProjet'
    )
    #nature_tuteur = models.PositiveSmallIntegerField(_("Nature Tuteur"), blank=True, null=True, choices=NATURE_TUTEUR, default=1)
    intitule = models.CharField(_("Intitulé"), max_length=200)
    date_demande = models.DateField(_('Date demande'), null=True, blank=True)
    description = models.CharField(_("Description"), max_length=500, blank=True)
    montant_total = models.DecimalField(_("Montant Global"), decimal_places=2, max_digits=10)
    montant_demande = models.DecimalField(_("Montant Demandé"), decimal_places=2, max_digits=10)
    montant_contribution = models.DecimalField(_("Contribution Personnelle"), decimal_places=2, max_digits=10, default=0)
    secteur = models.PositiveSmallIntegerField(_("Secteur"), blank=True, null=True, choices=SECTEUR_CHOIX )
    forme_juridique = models.PositiveSmallIntegerField(_("Forme Juridique"), blank=True, null=True, choices=FORME_JURIDIQUE_CHOIX)
    nature = models.PositiveSmallIntegerField(_("Nature projet"), blank=True, null=True, choices=NATURE_PROJET, default=1)
    lieu_region = models.ForeignKey(
        Region,
        verbose_name = _("Région Implantation"),
        related_name = "projets",
        on_delete = models.SET_NULL,
        null = True
    )
    lieu_province = models.ForeignKey(
        Province,
        on_delete = models.CASCADE,
        related_name = "projets",
        verbose_name = _("Province Implantation")
    )
    lieu_commune = models.ForeignKey(
        Commune,
        on_delete = models.CASCADE,
        related_name = "projets",
        verbose_name = _("Commune Implantation")
    )
    lieu_adresse = models.CharField(_("Lieu Implantation"), max_length=20, default=_("Guelmim"))
    piece_cin = models.BooleanField(_("Copie CIN"), choices=PIECE_CHOIX, default=False)
    piece_ramed = models.BooleanField(_("Copie RAMED"), default=False, choices=PIECE_CHOIX)
    piece_certificat = models.BooleanField(_("Certificat Médical"), default=False, choices=PIECE_CHOIX)
    piece_engagement = models.BooleanField(_("Engagement"), default=False, choices=PIECE_CHOIX)
    piece_devis = models.BooleanField(_("Devis"), default=False, choices=PIECE_CHOIX)
    piece_local = models.BooleanField(_("Local"), default=False, choices=PIECE_CHOIX)
    piece_conv_accom = models.BooleanField(_("Convention accompagnement"), default=False, choices=PIECE_CHOIX)
    piece_conv_finan = models.BooleanField(_("Convention Financement"), default=False, choices=PIECE_CHOIX)
    num_cheque = models.CharField(_("Num Chèque"), max_length=20, blank=True, null=True)
    date_cheque = models.DateField(_('Date Chèque'), null=True, blank=True)
    date_lancement = models.DateField(_('Date lancement'), null=True, blank=True)
    etape = models.ManyToManyField(
        EtapeProjet,
        related_name = "projets",
        verbose_name = _('Etape'),
        blank = True,
        through = 'SuiviProjet'
    )
    session = models.ForeignKey(Session, related_name="projets", on_delete=models.SET_NULL, null=True, verbose_name=_("Session"))

    def __str__(self):
        return "{}".format(self.intitule)

    class Meta:
        verbose_name = _('Projet')
        verbose_name_plural = _('Projets')

    def get_montant_approuve(self):
        return self.montant_demande

    def dossier_est_complet(self):
        if self.piece_cin and self.piece_engagement and self.piece_certificat and self.piece_devis:
            return _("Oui")
        else:
            return _("Non")
    dossier_est_complet.short_description = _("Dossier Complet")

    def get_etape(self):
        ordre = ""
        if self.suivi.count():
            dates = [x.date_etap for x in self.suivi.all()]
            ordres = [x.etape.ordre for x in self.suivi.all()]
            max_dates = max(dates)
            max_ordre = max(ordres)
            etape = self.suivi.get(date_etap=max_dates, etape__ordre=max_ordre)
            ordre = etape.etape.nom
        else:
            ordre = ""
        return ordre
    get_etape.short_description = _("Etape")

    def get_etape_date(self):
        ordre = ""
        if self.suivi.count():
            dates = [x.date_etap for x in self.suivi.all()]
            ordres = [x.etape.ordre for x in self.suivi.all()]
            max_dates = max(dates)
            max_ordre = max(ordres)
            etape = self.suivi.get(date_etap=max_dates, etape__ordre=max_ordre)
            ordre = etape.date_etap
        else:
            ordre = ""
        return ordre
    get_etape_date.short_description = _("Date étape")

    def get_etape_commentaire(self):
        ordre = ""
        if self.suivi.count():
            dates = [x.date_etap for x in self.suivi.all()]
            ordres = [x.etape.ordre for x in self.suivi.all()]
            max_dates = max(dates)
            max_ordre = max(ordres)
            etape = self.suivi.get(date_etap=max_dates, etape__ordre=max_ordre)
            ordre = etape.commentaire
        else:
            ordre = ""
        return ordre
    get_etape_commentaire.short_description = _("Commentaire")

    def get_etape_avancement(self):
        avancement = 0
        if self.suivi.count():
            dates = [x.date_etap for x in self.suivi.all()]
            ordres = [x.etape.ordre for x in self.suivi.all()]
            max_dates = max(dates)
            max_ordre = max(ordres)
            etape = self.suivi.get(date_etap=max_dates, etape__ordre=max_ordre)
            avancement = etape.avancement
        return avancement
    get_etape_avancement.short_description = _("Avancement")

    @mark_safe
    def get_beneficiaires(self):
        data ="<ul>"
        for ben in self.porteur.all():
            data += "<li>"+ ben.beneficiaire.__str__() +"</li>"
        data += "</ul>"
        return data
    get_beneficiaires.allow_tags=True
    get_beneficiaires.short_description=_("Bénéficiaires")



COMMISSION_CHOIX = (
    (1, _('PROVINCIALE')),
    (2, _('REGIONALE')),
    (3, _('CENTRALE')),
)

DECISION_CHOIX = (
    (1, _('VALIDE')),
    (2, _('REJETE')),
    (3, _('A REFAIRE')),
)


class Avis(models.Model):
    projet = models.ForeignKey(
        Projet,
        on_delete = models.CASCADE,
        verbose_name = _("Projet"),
        related_name = "avis"
    )
    commission = models.PositiveSmallIntegerField(_("Commission"), choices=COMMISSION_CHOIX)
    date_avis = models.DateField(_('Date avis'))
    num_pv = models.CharField(_('Numéro PV'), blank=True, max_length=10, null=True)
    decision = models.PositiveSmallIntegerField(_("Décision"), choices=DECISION_CHOIX)
    note = models.PositiveSmallIntegerField(_("Note"), default=0)
    observation = models.CharField(_('Observation'), blank=True, max_length=700, null=True)
    montant_approuve = models.DecimalField(_('Montant approuvé'), decimal_places=2, max_digits=10,  blank=True, null=True)
    nbre_tranche = models.PositiveSmallIntegerField(_('Nombre tranches'), blank=True, null=True)

    def __str__(self):
        return "{} | {}".format(self.get_commission_display(), self.date_avis)

    class Meta:
        verbose_name = _('Avis')
        verbose_name_plural = _('Avis')


class Visite(models.Model):

frontend/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="username", max_length=100, required=True)
    password = forms.CharField(label="password", max_length=200, required=True)

projets/forms.py
from django import forms
from .models import Projet


class ProjetForm(forms.ModelForm):
    class Meta:
        model = Projet
        fields = '__all__'

centres/views.py
from django.shortcuts import render

projets/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/frontend/projet_add.html
{% extends "frontend/index.html" %}
{% load static %}{% load l10n %}
{% block extrahead %}
<style>
.scrollview {
  overflow-x: scroll;
  overflow-y: hidden;
  white-space: nowrap;
}
</style>
{% endblock %}
{% block content %}
<div class="row gx-1 gx-lg-5 align-items-center my-5 justify-content-center">
    <div class="col-12 d-flex justify-content-center">
        {{ form.as_p }}
    </div>
</div>
{% endblock %}
{% block extrascripts %}
{% endblock %}

frontend/templates/frontend/projets.html
{% extends "frontend/index.html" %}
{% load static %}{% load l10n %}
{% block extrahead %}
<style>
    .scrollview {
        overflow-x: scroll;
        overflow-y: hidden;
        white-space: nowrap;
    }
    .card:hover {
        transform: scale(1.0);
        z-index:-1;
    }
</style>
{% endblock %}
{% block content %}
<div class="row gx-1 gx-lg-5 align-items-center my-5 justify-content-center">
    <div class="col-12 d-flex justify-content-center">
        <div class="card h-100 col-12 col-sm-12 shadow">
            <div class="card-header text-center">
                <h4 class="font-weight-light"> لائحة طلبات دعم المشاريع المدرة للدخل</h4>
            </div>
            <div class="card-body justify-content-between">
                <form class="form row gx-md-2 gx-1 col-12 gy-sm-2" method="get">
                    <div class="col-md-3 col-sm-4">
                        <select class="form-select text-center h-100" name="region" id="region" placeholder="الجهة" {% if region_disabled %}disabled{% endif %}>
                            <option value="0">الجهة</option>
                            {% for region in regions %}
                                <option value="{{ region.pk }}" {% if region.pk == region_selected.pk %}selected{% endif %}>{{ region.nom}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3 col-sm-4">
                        <select class="form-select text-center  h-100" name="province" id="province" placeholder="الإقليم" {% if province_disabled %}disabled{% endif %}>
                            <option value="0">الإقليم</option>
                            {% if region_selected != 0 %}
                            {% for province in provinces %}
                                <option value="{{ province.pk }}" {% if province.pk == province_selected.pk %}selected{% endif %}>{{ province.nom}}</option>
                            {% endfor %}
                            {% else %}
                            {% for region in regions %}
                            <optgroup label="{{ region.nom }}">
                            {% for province in region.provinces.all %}
                                <option value="{{ province.pk }}" {% if province.pk == province_selected.pk %}selected{% endif %}>{{ province.nom}}</option>
                            {% endfor %}
                            </optgroup>
                            {% endfor %}
                            {% endif %}
                        </select>
                    </div>
                    <div class="col-md-3 col-sm4">
                        <select class="form-select text-center  h-100" name="commune" id="commune" placeholder="الجماعة" {% if commune_disabled %}disabled{% endif %}>
                            <option value="0">الجماعة</option>
                            {% if province_selected != 0 %}
                            {% for commune in communes %}
                            <option value="{{ commune.pk }}" {% if commune.pk == commune_selected %}selected{% endif %}>{{ commune.nom}}</option>
                            {% endfor %}
                            {% else %}
                            {% for province in provinces %}
                            <optgroup label="{{ province.nom }}">
                            {% for commune in province.communes.all %}
                                <option value="{{ commune.pk }}" {% if commune.pk == commune_selected %}selected{% endif %}>{{ commune.nom}}</option>
                            {% endfor %}
                            </optgroup>
                            {% endfor %}
                            {% endif %}
                        </select>
                    </div>
                    <div class="col-md-2 col-sm-6 h-50">
                        <input class="form-control h-50" type="text" name="num_demande" placeholder="قم بإدخال رقم الطلب هنا" id="numeroD" {% if demande %}value="{{ demande }}"{% endif %}/>
                      </div>
                    <div class="col-1">
                        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-solid fa-magnifying-glass">البحث</i></button>
                    </div>
                </form>
            </div>
            <!--
            <div class="card-footer col-12 text-center">
                <button class="btn btn-primary" type="submit"><i class="fa-solid fa-solid fa-magnifying-glass"></i></button>
            </div> -->
        </div>
    </div>
</div>
<div class="row gx-4 gx-lg-5 align-items-center my-5 scrollview">
    <div class="col-sm-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>رقم الطلب </th>
                    <th>اسم المشروع</th>
                    <th>القطاع</th>
                    <th>المبلغ المطلوب</th>
                    <th>المرحلة</th>
                    <th>تاريخ المرحلة</th>
                    <th>نسبة التقدم</th>
                    <th>التفاصيل</th>
                </tr>
            </thead>
            <tbody>
                {% for projet in projets %}
                <tr>
                    <td>{{ projet.id }}</td>
                    <td>{{ projet.intitule }}</td>
                    <td>{{ projet.get_secteur_display }}</td>
                    <td>{{ projet.montant_demande }}</td>
                    <td>{{ projet.get_etape }}</td>
                    <td>{{ projet.get_etape_date }}</td>
                    <td class="text-center">
                    {{ projet.get_etape_avancement }}%
                    </td>
                    <td><a href="{% url 'f-details-agr' num_demande=projet.pk %}" alt="détails"><i class="fas fa-eye"></i> </a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
{% endblock %}
{% block extrascripts %}
<script>
$(document).ready(function() {
    $('select#region').select2({
        theme: "classic",
    });
    $('select#province').select2({
        theme: "classic"
    });
    $('select#commune').select2({
        theme: "classic"
    });
});
</script>
{% endblock %}

frontend/templates/frontend/projets_back.html
{% extends "frontend/index.html" %}
{% load static %}{% load l10n %}
{% block extrahead %}
<style>
.scrollview {
  overflow-x: scroll;
  overflow-y: hidden;
  white-space: nowrap;
}
</style>
{% endblock %}
{% block content %}
<div class="row gx-1 gx-lg-5 align-items-center my-5 justify-content-center">
    <div class="col-12 d-flex justify-content-center">
        <div class="card h-100 col-12 col-sm-12 shadow">
            <div class="card-header text-center">
                <h4 class="font-weight-light"> لائحة طلبات دعم المشاريع المدرة للدخل</h4>
            </div>
            <div class="card-body justify-content-between">
                <form class="form row gx-md-4 gx-2 col-8" method="get">
                    <div class="col-5">
                        <select class="form-select text-center" name="region" id="region" placeholder="الجهة" {% if region_disabled %}disabled{% endif %}>
                            <option value="0">الجهة</option>
                            {% for region in regions %}
                                <option value="{{ region.pk }}" {% if region.pk == region_selected %}selected{% endif %}>{{ region.nom}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-5">
                        <select class="form-select text-center" name="province" id="province" placeholder="الإقليم" {% if province_disabled %}disabled{% endif %}>
                            <option value="0">الإقليم</option>
                            {% for province in provinces %}
                                <option value="{{ province.pk }}" {% if province.pk == province_selected %}selected{% endif %}>{{ province.nom}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-2">
                        <button class="btn btn-primary" type="submit" {% if region_disabled and province_disabled %}disabled{% endif %}><i class="fa-solid fa-solid fa-magnifying-glass">البحث</i></button>
                    </div>
                </form>
                <form method="get" class="form row d-flex align-items-center justify-content-center">
                      <div class="col-8">
                        <input class="form-control" type="text" required name="num_demande" placeholder="قم بإدخال رقم الطلب هنا" id="numeroD"/>
                      </div>
                      <div class="col-4">
                        <button class="btn btn-primary" id="get_dem" type="sumbit" value="لبحث"><i class="fas fa-search"></i></button>
                      </div>
                </form>
            </div>
            <!--
            <div class="card-footer col-12 text-center">
                <button class="btn btn-primary" type="submit"><i class="fa-solid fa-solid fa-magnifying-glass"></i></button>
            </div> -->
        </div>
    </div>
</div>
<div class="row gx-4 gx-lg-5 align-items-center my-5 scrollview">
    <div class="col-sm-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>رقم الطلب </th>
                    <th>اسم المشروع</th>
                    <th>القطاع</th>
                    <th>المرحلة</th>
                    <th>تاريخ المرحلة</th>
                    <th>المبلغ المطلوب</th>
                    <th>التفاصيل</th>
                </tr>
            </thead>
            <tbody>
                {% for projet in projets %}
                <tr>
                    <td>{{ projet.id }}</td>
                    <td>{{ projet.intitule }}</td>
                    <td>{{ projet.get_secteur_display }}</td>
                    <td>{{ projet.get_etape }}</td>
                    <td>{{ projet.get_etape_date }}</td>
                    <td>{{ projet.montant_demande }}</td>
                    <td><a href="{% url 'f-details-agr' num_demande=projet.pk %}" alt="détails"><i class="fas fa-eye"></i> </a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
{% endblock %}
{% block extrascripts %}
{% endblock %}